#!/usr/bin/env bash
#
# Tests for the optional CGCR (Codex Goal with Claude Review) workflow wiring.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/test-helpers.sh"

README="$PROJECT_ROOT/README.md"
USAGE_DOC="$PROJECT_ROOT/docs/usage.md"
CGCR_DOC="$PROJECT_ROOT/docs/cgcr.md"
CGCR_LONGFORM_DOC="$PROJECT_ROOT/docs/codex-goal-claude-review.md"
CGCR_STATE_MACHINE="$PROJECT_ROOT/references/cgcr-state-machine.md"
CGCR_LONGFORM_STATE_MACHINE="$PROJECT_ROOT/references/codex-goal-monitor-state-machine.md"
CLAUDE_INSTALL_DOC="$PROJECT_ROOT/docs/install-for-claude.md"
CODEX_INSTALL_DOC="$PROJECT_ROOT/docs/install-for-codex.md"
INSTALL_SCRIPT="$PROJECT_ROOT/scripts/install-skill.sh"
STEER_HOOK="$PROJECT_ROOT/hooks/cgcr-steer-prompt-hook.sh"
CODEX_GOAL_SKILL="$PROJECT_ROOT/skills/humanize-codex-goal/SKILL.md"
CGCR_LAUNCHER_SKILL="$PROJECT_ROOT/skills/humanize-cgcr/SKILL.md"
MONITOR_SKILL="$PROJECT_ROOT/skills/monitor-codex-goal/SKILL.md"
CGCR_COMMAND="$PROJECT_ROOT/commands/cgcr.md"
MONITOR_COMMAND="$PROJECT_ROOT/commands/monitor-codex-goal.md"
RLCR_COMMAND="$PROJECT_ROOT/commands/start-rlcr-loop.md"
RLCR_SKILL="$PROJECT_ROOT/skills/humanize-rlcr/SKILL.md"

assert_file_exists() {
    local file="$1" desc="$2"
    if [[ -f "$file" ]]; then
        pass "$desc"
    else
        fail "$desc" "$file exists" "missing"
    fi
}

assert_contains() {
    local file="$1" needle="$2" desc="$3"
    if grep -qF -- "$needle" "$file"; then
        pass "$desc"
    else
        fail "$desc" "$needle" "not found in $file"
    fi
}

assert_not_contains() {
    local file="$1" needle="$2" desc="$3"
    if grep -qF -- "$needle" "$file"; then
        fail "$desc" "absent: $needle" "found in $file"
    else
        pass "$desc"
    fi
}

echo "=========================================="
echo "CGCR Workflow Tests"
echo "=========================================="
echo ""

assert_file_exists "$CODEX_GOAL_SKILL" "Codex-side goal skill exists"
assert_file_exists "$CGCR_LAUNCHER_SKILL" "Codex-side CGCR launcher skill exists"
assert_file_exists "$MONITOR_SKILL" "Claude-side monitor skill exists"
assert_file_exists "$CGCR_COMMAND" "Canonical CGCR command wrapper exists"
assert_file_exists "$MONITOR_COMMAND" "Claude command wrapper exists"
assert_file_exists "$CGCR_DOC" "Canonical CGCR doc exists"
assert_file_exists "$CGCR_LONGFORM_DOC" "Long-form CGCR doc still exists"
assert_file_exists "$CGCR_STATE_MACHINE" "Canonical CGCR state machine exists"
assert_file_exists "$CGCR_LONGFORM_STATE_MACHINE" "Long-form CGCR state machine still exists"
assert_file_exists "$STEER_HOOK" "CGCR steer prompt hook exists"
assert_file_exists "$RLCR_COMMAND" "Existing RLCR command still exists"
assert_file_exists "$RLCR_SKILL" "Existing RLCR skill still exists"

assert_contains "$CODEX_GOAL_SKILL" "[GOAL-BINDING]" "Codex goal skill defines binding block"
assert_contains "$CODEX_GOAL_SKILL" "MONITOR_TARGET_ID:" "Codex goal skill defines monitor target id"
assert_contains "$CODEX_GOAL_SKILL" "[CHECKPOINT:<phase-name>]" "Codex goal skill defines checkpoints"
assert_contains "$CODEX_GOAL_SKILL" "[MONITOR-ACK]" "Codex goal skill defines monitor acknowledgement"
assert_contains "$CODEX_GOAL_SKILL" "[GOAL-CLOSEOUT]" "Codex goal skill defines closeout"
assert_contains "$CODEX_GOAL_SKILL" "Never claim tests passed unless the exact command was actually run" "Codex goal skill forbids fabricated test claims"
assert_contains "$CODEX_GOAL_SKILL" 'Codex optional flow skill: `/flow:humanize-codex-goal`' "Codex goal skill names Codex-side flow"
assert_contains "$CODEX_GOAL_SKILL" 'Claude Code monitor command: `/humanize:monitor-codex-goal`' "Codex goal skill distinguishes Claude monitor command"

assert_contains "$CGCR_LAUNCHER_SKILL" "name: humanize-cgcr" "CGCR launcher skill has correct name"
assert_contains "$CGCR_LAUNCHER_SKILL" "type: flow" "CGCR launcher skill is a Codex flow"
assert_contains "$CGCR_LAUNCHER_SKILL" "/flow:humanize-cgcr" "CGCR launcher documents Codex flow command"
assert_contains "$CGCR_LAUNCHER_SKILL" '`/humanize:cgcr` is the public CGCR command name.' "CGCR launcher documents canonical command wrapper"
assert_contains "$CGCR_LAUNCHER_SKILL" "[GOAL-BINDING]" "CGCR launcher directly requires goal binding marker"
assert_contains "$CGCR_LAUNCHER_SKILL" "[CHECKPOINT:<phase-name>]" "CGCR launcher directly requires checkpoint marker"
assert_contains "$CGCR_LAUNCHER_SKILL" "[MONITOR-ACK]" "CGCR launcher directly requires monitor acknowledgement marker"
assert_contains "$CGCR_LAUNCHER_SKILL" "[GOAL-CLOSEOUT]" "CGCR launcher directly requires closeout marker"
assert_contains "$CGCR_LAUNCHER_SKILL" "setup-cgcr.sh" "CGCR launcher delegates to setup script"
assert_contains "$CGCR_LAUNCHER_SKILL" "Codex is the only implementation agent" "CGCR launcher preserves executor boundary"

assert_contains "$CGCR_COMMAND" "/humanize:cgcr" "Canonical command documents public CGCR command"
assert_contains "$CGCR_COMMAND" "RLCR = Claude Code implements, Codex reviews" "Canonical command distinguishes RLCR roles"
assert_contains "$CGCR_COMMAND" 'CGCR = Codex `/goal` implements, Claude Code reviews and monitors' "Canonical command distinguishes CGCR roles"
assert_contains "$CGCR_COMMAND" "/flow:humanize-cgcr" "Canonical command delegates to CGCR flow"
assert_contains "$CGCR_COMMAND" "commands/monitor-codex-goal.md" "Canonical command points to lower-level monitor details"
assert_contains "$CGCR_COMMAND" "/humanize:cgcr --discover --notify-only" "Canonical command includes discover example"
assert_contains "$CGCR_COMMAND" "--manual-loop" "Canonical command includes manual-loop example"

assert_contains "$MONITOR_SKILL" "Forbidden Operations" "Monitor skill contains forbidden operation list"
assert_contains "$MONITOR_SKILL" "CGCR is not a dual-executor system" "Monitor skill rejects dual-executor CGCR"
assert_contains "$MONITOR_SKILL" "Codex is the only implementation agent" "Monitor skill names Codex as only implementation agent"
assert_contains "$MONITOR_SKILL" "reject that design and document why" "Monitor skill rejects Claude-mutating designs"
assert_contains "$MONITOR_SKILL" "apply_patch" "Monitor skill forbids apply_patch"
assert_contains "$MONITOR_SKILL" "git add" "Monitor skill forbids git add"
assert_contains "$MONITOR_SKILL" "git commit" "Monitor skill forbids git commit"
assert_contains "$MONITOR_SKILL" "build commands" "Monitor skill forbids build commands"
assert_contains "$MONITOR_SKILL" "package install" "Monitor skill forbids package install"
assert_contains "$MONITOR_SKILL" "Binding Rules" "Monitor skill contains binding rules"
assert_contains "$MONITOR_SKILL" "This is a Claude Code monitor skill. It is not a Codex command." "Monitor skill distinguishes Claude side"
assert_contains "$MONITOR_SKILL" 'Codex-side executor command: `/goal`' "Monitor skill names Codex /goal separately"
assert_contains "$MONITOR_SKILL" "CGCR requires a verified tmux target for injection" "Monitor skill requires tmux target for injection"
assert_contains "$MONITOR_SKILL" "codex_session_id" "Monitor skill binds by Codex session id"
assert_contains "$MONITOR_SKILL" "tmux_target" "Monitor skill binds by tmux target"
assert_contains "$MONITOR_SKILL" "MONITOR_TARGET_ID" "Monitor skill binds by monitor target id"
assert_contains "$MONITOR_SKILL" "Automatic injection is allowed only when all conditions are true" "Monitor skill documents auto-injection gate"
assert_contains "$MONITOR_SKILL" "tmux send-keys -l" "Monitor skill documents literal tmux injection"
assert_contains "$MONITOR_SKILL" "cgcr-steer-prompt-hook.sh" "Monitor skill uses CGCR steer prompt hook"
assert_contains "$MONITOR_SKILL" "If no drift is found" "Monitor skill gates correction on drift judgment"
assert_contains "$MONITOR_SKILL" 'correction count `4, 8, 12, ...`' "Monitor skill documents Occam selector branch"
assert_contains "$MONITOR_SKILL" "Do not include the internal selector" "Monitor skill hides selector metadata from prompt"
assert_contains "$MONITOR_SKILL" "--once" "Monitor skill supports --once alias"
assert_contains "$MONITOR_SKILL" "--no-cron" "Monitor skill supports --no-cron alias"
assert_contains "$MONITOR_SKILL" "State And Checkpoints" "Monitor skill documents checkpoint state"
assert_contains "$MONITOR_SKILL" "Transcript progress" "Monitor skill documents transcript inspection"
assert_contains "$MONITOR_SKILL" "Repository delta" "Monitor skill documents repository delta inspection"
assert_contains "$MONITOR_SKILL" "Artifact reasonableness" "Monitor skill documents artifact inspection"
assert_contains "$MONITOR_SKILL" '"CronCreate"' "Monitor skill allows CronCreate"
assert_contains "$MONITOR_SKILL" '"CronDelete"' "Monitor skill allows CronDelete"
assert_contains "$MONITOR_SKILL" '"PushNotification"' "Monitor skill allows PushNotification"
assert_contains "$MONITOR_SKILL" "prompt must re-enter the monitor for one tick only" "Monitor skill prevents recursive cron scheduling"

assert_contains "$MONITOR_COMMAND" "/humanize:monitor-codex-goal" "Monitor command documents Humanize command name"
assert_contains "$MONITOR_COMMAND" "This is a Claude Code command. It is not a Codex command." "Monitor command distinguishes Claude command"
assert_contains "$MONITOR_COMMAND" '| Codex | `/goal` |' "Monitor command lists Codex command separately"
assert_contains "$MONITOR_COMMAND" "This is **not RLCR**" "Monitor command distinguishes CGCR from RLCR"
assert_contains "$MONITOR_COMMAND" "not a dual-executor system" "Monitor command rejects dual-executor framing"
assert_contains "$MONITOR_COMMAND" "--once" "Monitor command supports --once alias"
assert_contains "$MONITOR_COMMAND" "--no-cron" "Monitor command supports --no-cron alias"
assert_contains "$MONITOR_COMMAND" '"CronCreate"' "Monitor command allows CronCreate"
assert_contains "$MONITOR_COMMAND" "prompt must include" "Monitor command prevents recursive cron scheduling"
assert_contains "$MONITOR_COMMAND" "one tmux pane/window runs Codex" "Monitor command requires tmux topology"
assert_contains "$MONITOR_COMMAND" "AskUserQuestion" "Monitor command allows user approval path"
assert_contains "$MONITOR_COMMAND" "cgcr-steer-prompt-hook.sh" "Monitor command documents steer prompt hook"

assert_contains "$CGCR_DOC" "RLCR" "CGCR doc mentions RLCR"
assert_contains "$CGCR_DOC" "CGCR" "CGCR doc mentions CGCR"
assert_contains "$CGCR_DOC" "Claude Code implements" "CGCR doc documents RLCR executor"
assert_contains "$CGCR_DOC" 'Codex `/goal` or `/flow:humanize-cgcr`' "CGCR doc documents CGCR executor"
assert_contains "$CGCR_DOC" "/humanize:start-rlcr-loop" "CGCR doc preserves RLCR command reference"
assert_contains "$CGCR_DOC" "/humanize:cgcr" "CGCR doc documents canonical command"
assert_contains "$CGCR_DOC" "/humanize:monitor-codex-goal" "CGCR doc documents lower-level monitor command"
assert_contains "$CGCR_DOC" "CGCR expects two tmux panes or windows" "CGCR doc requires two-tmux layout"
assert_contains "$CGCR_DOC" "MONITOR_TARGET_ID" "CGCR doc documents monitor target id"
assert_contains "$CGCR_DOC" "[MONITOR]" "CGCR doc documents monitor injection"
assert_contains "$CGCR_DOC" "read-only by default" "CGCR doc says Claude is read-only by default"
assert_contains "$CGCR_DOC" "not a second executor" "CGCR doc rejects second executor"
assert_contains "$CGCR_DOC" "Failure Modes" "CGCR doc documents failure modes"
assert_contains "$CGCR_DOC" "Exact Binding" "CGCR doc documents exact binding"
assert_contains "$CGCR_DOC" "Steer Prompt Selection" "CGCR doc documents steer prompt selection"
assert_contains "$CGCR_DOC" "judge drift" "CGCR doc documents drift gate before correction"
assert_contains "$CGCR_DOC" "correction_count = prior_same_goal_correction_count + 1" "CGCR doc documents correction count increment"
assert_contains "$CGCR_DOC" "Long Prompt Startup Protocol" "CGCR doc documents long prompt startup protocol"
assert_contains "$CGCR_DOC" "start-codex.sh" "CGCR doc documents short Codex launcher"
assert_contains "$CGCR_DOC" "The tmux layer must not carry large prompt" "CGCR doc keeps long prompts out of tmux input"

assert_contains "$CGCR_LONGFORM_DOC" "/humanize:cgcr" "Long-form CGCR doc mentions canonical command"
assert_contains "$CGCR_LONGFORM_DOC" "start-codex.sh" "Long-form CGCR doc documents short Codex launcher"
assert_contains "$CGCR_LONGFORM_DOC" "tmux only receives short launcher paths" "Long-form CGCR doc keeps tmux prompt input short"
assert_contains "$CGCR_STATE_MACHINE" "UNBOUND" "Canonical state machine includes UNBOUND"
assert_contains "$CGCR_STATE_MACHINE" "DISCOVERING" "Canonical state machine includes DISCOVERING"
assert_contains "$CGCR_STATE_MACHINE" "BOUND_READ_ONLY" "Canonical state machine includes BOUND_READ_ONLY"
assert_contains "$CGCR_STATE_MACHINE" "TICK_RUNNING" "Canonical state machine includes TICK_RUNNING"
assert_contains "$CGCR_STATE_MACHINE" "CLEAN" "Canonical state machine includes CLEAN"
assert_contains "$CGCR_STATE_MACHINE" "NEEDS_NOTIFY" "Canonical state machine includes NEEDS_NOTIFY"
assert_contains "$CGCR_STATE_MACHINE" "DRAFT_PENDING" "Canonical state machine includes DRAFT_PENDING"
assert_contains "$CGCR_STATE_MACHINE" "APPROVED_TO_INJECT" "Canonical state machine includes APPROVED_TO_INJECT"
assert_contains "$CGCR_STATE_MACHINE" "AUTO_INJECT_ELIGIBLE" "Canonical state machine includes AUTO_INJECT_ELIGIBLE"
assert_contains "$CGCR_STATE_MACHINE" "INJECTING" "Canonical state machine includes INJECTING"
assert_contains "$CGCR_STATE_MACHINE" "COOLDOWN" "Canonical state machine includes COOLDOWN"
assert_contains "$CGCR_STATE_MACHINE" "TERMINAL" "Canonical state machine includes TERMINAL"

assert_contains "$README" "Optional: Codex Goal with Claude Review" "README documents optional CGCR workflow"
assert_contains "$README" "Claude Code implements, Codex reviews" "README distinguishes RLCR roles"
assert_contains "$README" '/humanize:cgcr` = public CGCR command wrapper' "README labels canonical CGCR command"
assert_contains "$README" '/humanize:monitor-codex-goal` in Claude Code' "README labels lower-level Claude monitor command"
assert_contains "$README" '$humanize-cgcr` in the Codex terminal' "README labels Codex terminal launcher command"
assert_contains "$README" "In the **Codex terminal input**, type:" "README tells users where to type CGCR command"
assert_contains "$README" '$humanize-cgcr <your long task prompt>' "README documents Codex terminal usage"
assert_contains "$README" "Recommended long task prompt format:" "README documents long task prompt format"
assert_contains "$README" "Tools and skills:" "README prompts users to specify tools and skills"
assert_contains "$README" "Key flow:" "README prompts users to specify key flow"
assert_contains "$README" "Constraints and stop conditions:" "README prompts users to specify constraints and stop conditions"
assert_contains "$README" "Notes:" "README prompts users to specify notes"
assert_contains "$README" "Do not type this inside tmux." "README clarifies tmux is created by launcher"
assert_contains "$README" 'Inside tmux there are two windows: `codex-goal` and `claude-monitor`.' "README documents CGCR tmux windows"
assert_contains "$README" '/flow:humanize-cgcr` = lower-level Codex flow shim' "README labels lower-level Codex flow shim"
assert_contains "$README" "[CGCR](docs/cgcr.md)" "README links canonical CGCR doc"
assert_contains "$USAGE_DOC" "/humanize:cgcr <task>" "Usage guide includes canonical CGCR command"
assert_contains "$USAGE_DOC" "/humanize:monitor-codex-goal <session-id> <tmux-target>" "Usage guide includes Claude monitor command"
assert_contains "$USAGE_DOC" "/flow:humanize-cgcr <task>" "Usage guide includes Codex launcher command"
assert_contains "$CLAUDE_INSTALL_DOC" "/humanize:cgcr" "Claude install doc lists canonical CGCR command"
assert_contains "$CLAUDE_INSTALL_DOC" "/humanize:monitor-codex-goal" "Claude install doc lists monitor command"
assert_contains "$CODEX_INSTALL_DOC" "humanize-codex-goal" "Codex install doc lists Codex goal skill"
assert_contains "$CODEX_INSTALL_DOC" "humanize-cgcr" "Codex install doc lists Codex launcher skill"
assert_contains "$CODEX_INSTALL_DOC" "monitor-codex-goal should not be treated as a Codex executor skill" "Codex install doc clarifies monitor installer semantics"

assert_contains "$INSTALL_SCRIPT" "CODEX_SKILL_NAMES" "Installer has Codex-specific skill group"
assert_contains "$INSTALL_SCRIPT" "humanize-codex-goal" "Installer recognizes humanize-codex-goal"
assert_contains "$INSTALL_SCRIPT" "humanize-cgcr" "Installer recognizes humanize-cgcr"
assert_contains "$INSTALL_SCRIPT" "humanize-rlcr" "Installer still includes humanize-rlcr"
assert_not_contains "$INSTALL_SCRIPT" "monitor-codex-goal" "Installer does not install Claude monitor as a Codex skill"

assert_contains "$RLCR_COMMAND" "/humanize:start-rlcr-loop" "RLCR command name remains documented"
assert_contains "$RLCR_SKILL" "name: humanize-rlcr" "RLCR skill name remains unchanged"

print_test_summary "CGCR Workflow Tests"
